require("dotenv").config();

module.exports = {
  port: process.env.PORT || 3000,
  nodeEnv: process.env.NODE_ENV || "development",

  whatsapp: {
    sessionPath: process.env.SESSION_PATH || "./session",
    puppeteer: {
      headless: "new",
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-accelerated-2d-canvas",
        "--disable-gpu",
        "--disable-web-security",
        "--disable-features=IsolateOrigins,site-per-process",
        "--disable-blink-features=AutomationControlled",
        "--disable-background-timer-throttling",
        "--disable-backgrounding-occluded-windows",
        "--disable-renderer-backgrounding",
        "--disable-wake-on-wake",
        "--disable-notifications",
        "--disable-geolocation",
        "--disable-sync",
        "--disable-default-apps",
        "--disable-extensions",
        "--disable-component-extensions-with-background-pages",
        "--disable-client-side-phishing-detection",
        "--disable-crash-reporter",
        "--disable-3d-apis",
        "--disable-ipc-flooding-protection",
        "--disable-site-isolation-trials",
        "--disable-pdf-viewer",
        "--disable-print-preview",
        "--disable-speech-api",
        "--disable-usb-keyboard-detect",
        "--disable-voice-input",
        "--disable-wake-on-wake",
        "--disable-webgl",
        "--disable-webgl2",
        "--mute-audio",
        "--no-default-browser-check",
        "--no-first-run",
        "--no-pings",
        "--no-service-autorun",
        "--password-store=basic",
        "--use-mock-keychain",
        "--disable-breadcrumb",
        "--disable-cache",
        "--disable-http-cache",
        "--disable-application-cache",
        "--disable-offline-load-stale-cache",
        "--disable-session-crashed-bubble",
        "--disable-infobars",
        "--disable-save-password-bubble",
        "--disable-translate",
        "--disable-features=ChromeWhatsNewUI",
        "--disable-features=ChromeTips",
        "--disable-features=PrivacySandboxSettings4",
        "--disable-features=PrivacySandboxSettings5",
      ],
      defaultViewport: {
        width: 1920,
        height: 1080,
        deviceScaleFactor: 1,
        hasTouch: false,
        isLandscape: true,
        isMobile: false,
      },
      ignoreDefaultArgs: ["--enable-automation"],
      timeout: 120000,
    },
  },

  api: {
    weatherKey: process.env.WEATHER_API_KEY,
  },
};
